### ISSUE TITLE
Cannot read properties of undefined (reading 'prototype')

### ISSUE THREAD

**Issue by ihorbond** [BedrockStreaming/superagent-mock#117]
Hey thanks for this package! I have the following issue: when it's used with https://www.npmjs.com/package/supertest
the following line breaks 
https://github.com/BedrockStreaming/superagent-mock/blob/v5.0.0/src/superagent-mock.js#L15

because the agent object exposed by supertest doesn't have a Request property, I'm assuming that's the issue
https://github.com/ladjs/supertest/blob/v6.3.3/lib/agent.js#L51

I know that it sounds like a supertest issue but was wondering if you'd be interested to update you plugin as well ?

**Comment by ihorbond** [comment]
for now I added it manually to the agent instance exposes by supertest:
`agent.Request = { prototype: { end: function () {} } };`

**Comment by fdubost** [comment]
Hi @ihorbond, thanks for your interest for this package 🙂
Fell free to make a PR to fix this issue with `supertest` 😉

**Comment by ihorbond** [comment]
@fdubost please take a look #118

**Comment by ihorbond** [comment]
@fdubost could you please merge the PR?

**Comment by fdubost** [comment]
@ihorbond it's done, sorry for the delay 😅
